<?php
/*
 * MODULO DE GESTION DE CONEXIONES SOAP CON WEBSERVICE SAGEC DE MRW
 *
 * El módulo hace el uso de la libreria SOAP de PHP5 para conexion y generacion
 * de envios entre Prestashop y el WebService SAGEC de MRW
 *
 * @author MRW Iberia - Dpto. Desarrollo <miguel.delahoz@mrw.es>
 * @copyright (c)2014 - MRW IBERIA
 * @version 1.0.11 - 31/01/2014
 *
 */

$tipovia = array(
    '1' => array('cod'=>'AB','nom'=>'ARRABAL'),
    '2' => array('cod'=>'AC','nom'=>'ACERA'),
    '3' => array('cod'=>'AD','nom'=>'ALDA'),
    '4' => array('cod'=>'AE','nom'=>'ACCESO'),
    '5' => array('cod'=>'AI','nom'=>'PATIO'),
    '6' => array('cod'=>'AL','nom'=>'ALAMEDA'),
    '7' => array('cod'=>'AN','nom'=>'ANTIGUO'),
    '8' => array('cod'=>'AO','nom'=>'ARCO'),
    '9' => array('cod'=>'AP','nom'=>'APARTAMENTO'),
    '10' => array('cod'=>'AR','nom'=>'ARA'),
    '11' => array('cod'=>'AS','nom'=>'CASAS'),
    '12' => array('cod'=>'AT','nom'=>'ALTO'),
    '13' => array('cod'=>'AU','nom'=>'AUTOVIA'),
    '14' => array('cod'=>'AV','nom'=>'AVENIDA'),
    '15' => array('cod'=>'AY','nom'=>'ARROYO'),
    '16' => array('cod'=>'AZ','nom'=>'PLAZUELA'),
    '17' => array('cod'=>'BA','nom'=>'BARRIADA'),
    '18' => array('cod'=>'BB','nom'=>'RCANTOS'),
    '19' => array('cod'=>'BJ','nom'=>'BAJADA'),
    '20' => array('cod'=>'BL','nom'=>'BLOQUE'),
    '21' => array('cod'=>'BO','nom'=>'BARRIO'),
    '22' => array('cod'=>'BR','nom'=>'BARRANCO'),
    '23' => array('cod'=>'BU','nom'=>'BULEVAR'),
    '24' => array('cod'=>'CA','nom'=>'CALLEJA'),
    '25' => array('cod'=>'CB','nom'=>'CIRCUNVALACION'),
    '26' => array('cod'=>'CC','nom'=>'CAMPO'),
    '27' => array('cod'=>'CD','nom'=>'CUADRA'),
    '28' => array('cod'=>'CE','nom'=>'CARRERA'),
    '29' => array('cod'=>'CG','nom'=>'COLGIO'),
    '30' => array('cod'=>'CH','nom'=>'CHALET'),
    '31' => array('cod'=>'CI','nom'=>'CARRIL'),
    '32' => array('cod'=>'CJ','nom'=>'CALLEJON'),
    '33' => array('cod'=>'CL','nom'=>'CALLE'),
    '34' => array('cod'=>'CM','nom'=>'CAMINO'),
    '35' => array('cod'=>'CN','nom'=>'CONJUNTO'),
    '36' => array('cod'=>'CÑ','nom'=>'CAÑADA'),
    '37' => array('cod'=>'CO','nom'=>'CORTIJO'),
    '38' => array('cod'=>'CP','nom'=>'CAMPING'),
    '39' => array('cod'=>'CQ','nom'=>'ACEQUIA'),
    '40' => array('cod'=>'CR','nom'=>'CARRETERA'),
    '41' => array('cod'=>'CS','nom'=>'CASERIO'),
    '42' => array('cod'=>'CT','nom'=>'CINTURON'),
    '43' => array('cod'=>'CU','nom'=>'CUESTA'),
    '44' => array('cod'=>'CV','nom'=>'CAMINO VIEJO'),
    '45' => array('cod'=>'CZ','nom'=>'CALZADA'),
    '46' => array('cod'=>'DA','nom'=>'RINCONADA'),
    '47' => array('cod'=>'DC','nom'=>'CORRDOR'),
    '48' => array('cod'=>'DE','nom'=>'DHESA'),
    '49' => array('cod'=>'DS','nom'=>'DISEMINADO'),
    '50' => array('cod'=>'EA','nom'=>'ESCALAS'),
    '51' => array('cod'=>'EC','nom'=>'ESTACION'),
    '52' => array('cod'=>'ED','nom'=>'DIFICIO'),
    '53' => array('cod'=>'EJ','nom'=>'CALLEJUELA'),
    '54' => array('cod'=>'EM','nom'=>'EXTRAMUROS'),
    '55' => array('cod'=>'EN','nom'=>'ENTRADA'),
    '56' => array('cod'=>'EO','nom'=>'CERRO'),
    '57' => array('cod'=>'ER','nom'=>'EXTRARRADIO'),
    '58' => array('cod'=>'ES','nom'=>'ESCALINATA'),
    '59' => array('cod'=>'ET','nom'=>'ESTRADA'),
    '60' => array('cod'=>'EX','nom'=>'EXPLANADA'),
    '61' => array('cod'=>'FC','nom'=>'FERROCARRIL'),
    '62' => array('cod'=>'FN','nom'=>'FINCA'),
    '63' => array('cod'=>'FU','nom'=>'FUENTE'),
    '64' => array('cod'=>'GL','nom'=>'GLORIETA'),
    '65' => array('cod'=>'GR','nom'=>'GRUPO'),
    '66' => array('cod'=>'GV','nom'=>'GRAN VIA'),
    '67' => array('cod'=>'HO','nom'=>'HORTA'),
    '68' => array('cod'=>'HT','nom'=>'HUERTA'),
    '69' => array('cod'=>'IN','nom'=>'RCINTO'),
    '70' => array('cod'=>'IS','nom'=>'ISLA'),
    '71' => array('cod'=>'IU','nom'=>'CIUDADELA'),
    '72' => array('cod'=>'JP','nom'=>'PARAJE'),
    '73' => array('cod'=>'JR','nom'=>'JARDINES'),
    '74' => array('cod'=>'KO','nom'=>'COOPERATIVA'),
    '75' => array('cod'=>'LA','nom'=>'PLACETA'),
    '76' => array('cod'=>'LD','nom'=>'LADO'),
    '77' => array('cod'=>'LG','nom'=>'LUGAR'),
    '78' => array('cod'=>'LL','nom'=>'PASILLO'),
    '79' => array('cod'=>'LM','nom'=>'LOMA'),
    '80' => array('cod'=>'LN','nom'=>'LLANO'),
    '81' => array('cod'=>'LQ','nom'=>'ALQUERIA'),
    '82' => array('cod'=>'MA','nom'=>'MALCON'),
    '83' => array('cod'=>'MC','nom'=>'MERCADO'),
    '84' => array('cod'=>'ML','nom'=>'MUELLE'),
    '85' => array('cod'=>'MN','nom'=>'MUNICIPIO'),
    '86' => array('cod'=>'MO','nom'=>'MONTAÑA'),
    '87' => array('cod'=>'MR','nom'=>'MONASTERIO'),
    '88' => array('cod'=>'EMS','nom'=>'MASIA'),
    '89' => array('cod'=>'MT','nom'=>'MONTE'),
    '90' => array('cod'=>'MU','nom'=>'MURO'),
    '91' => array('cod'=>'MZ','nom'=>'MANZANA'),
    '92' => array('cod'=>'NC','nom'=>'NUCLEO'),
    '93' => array('cod'=>'ND','nom'=>'NUDO'),
    '94' => array('cod'=>'NI','nom'=>'COSTANILLA'),
    '95' => array('cod'=>'NL','nom'=>'CANAL'),
    '96' => array('cod'=>'NO','nom'=>'PANTANO'),
    '97' => array('cod'=>'NR','nom'=>'ANDADOR'),
    '98' => array('cod'=>'NT','nom'=>'CANTON'),
    '99' => array('cod'=>'OA','nom'=>'CORRAL'),
    '100' => array('cod'=>'OE','nom'=>'COSTERA'),
    '101' => array('cod'=>'OL','nom'=>'COLONIA'),
    '102' => array('cod'=>'ON','nom'=>'CONVENTO'),
    '103' => array('cod'=>'OS','nom'=>'POSADA'),
    '104' => array('cod'=>'OT','nom'=>'POSTIGO'),
    '105' => array('cod'=>'PA','nom'=>'PARCELA'),
    '106' => array('cod'=>'PB','nom'=>'POBLADO'),
    '107' => array('cod'=>'PC','nom'=>'PARTICULAR'),
    '108' => array('cod'=>'PD','nom'=>'PARTIDA'),
    '109' => array('cod'=>'PE','nom'=>'PLAZOLETA'),
    '110' => array('cod'=>'PG','nom'=>'POLIGONO'),
    '111' => array('cod'=>'PI','nom'=>'PASADIZO'),
    '112' => array('cod'=>'PJ','nom'=>'PASAJE'),
    '113' => array('cod'=>'PL','nom'=>'PARALELA'),
    '114' => array('cod'=>'PM','nom'=>'PASEO MARITIMO'),
    '115' => array('cod'=>'PN','nom'=>'PARCELACION'),
    '116' => array('cod'=>'PO','nom'=>'PORTAL'),
    '117' => array('cod'=>'PP','nom'=>'PORTA'),
    '118' => array('cod'=>'PQ','nom'=>'PARROQUIA'),
    '119' => array('cod'=>'PR','nom'=>'PROLONGACION'),
    '120' => array('cod'=>'PS','nom'=>'PASEO'),
    '121' => array('cod'=>'PT','nom'=>'PUENTE'),
    '122' => array('cod'=>'PU','nom'=>'PUERTA'),
    '123' => array('cod'=>'PY','nom'=>'PLAYA'),
    '124' => array('cod'=>'PZ','nom'=>'PLAZA'),
    '125' => array('cod'=>'QE','nom'=>'PARQUE'),
    '126' => array('cod'=>'QT','nom'=>'QUINTA'),
    '127' => array('cod'=>'RA','nom'=>'RIBERA'),
    '128' => array('cod'=>'RB','nom'=>'RAMBLA'),
    '129' => array('cod'=>'RC','nom'=>'RINCON'),
    '130' => array('cod'=>'RD','nom'=>'RONDA'),
    '131' => array('cod'=>'RE','nom'=>'REPLACETA'),
    '132' => array('cod'=>'RI','nom'=>'RIO'),
    '133' => array('cod'=>'RL','nom'=>'RAVAL'),
    '134' => array('cod'=>'RM','nom'=>'RAMAL'),
    '135' => array('cod'=>'RN','nom'=>'RONDIN'),
    '136' => array('cod'=>'RO','nom'=>'ROTONDA'),
    '137' => array('cod'=>'RP','nom'=>'RAMPA'),
    '138' => array('cod'=>'RR','nom'=>'RIERA'),
    '139' => array('cod'=>'RS','nom'=>'RESIDENCIAL'),
    '140' => array('cod'=>'RT','nom'=>'RAMBLETA'),
    '141' => array('cod'=>'RU','nom'=>'CRUCE'),
    '142' => array('cod'=>'SA','nom'=>'SALON'),
    '143' => array('cod'=>'SB','nom'=>'SUBIDA'),
    '144' => array('cod'=>'SC','nom'=>'SCTOR'),
    '145' => array('cod'=>'SD','nom'=>'SENDA'),
    '146' => array('cod'=>'SE','nom'=>'SCCION'),
    '147' => array('cod'=>'SL','nom'=>'SOLAR'),
    '148' => array('cod'=>'SN','nom'=>'SENDERO'),
    '149' => array('cod'=>'SP','nom'=>'PASO'),
    '150' => array('cod'=>'SR','nom'=>'ESCALERA'),
    '151' => array('cod'=>'ST','nom'=>'SANTUARIO'),
    '152' => array('cod'=>'TA','nom'=>'COSTA'),
    '153' => array('cod'=>'TE','nom'=>'TRASERA'),
    '154' => array('cod'=>'TI','nom'=>'PORTICO'),
    '155' => array('cod'=>'TJ','nom'=>'ATAJO'),
    '156' => array('cod'=>'TL','nom'=>'TUNEL'),
    '157' => array('cod'=>'TN','nom'=>'TERRENOS'),
    '158' => array('cod'=>'TO','nom'=>'TORRENTE'),
    '159' => array('cod'=>'TP','nom'=>'AUTOPISTA'),
    '160' => array('cod'=>'TR','nom'=>'TRAVESIA'),
    '161' => array('cod'=>'TS','nom'=>'TRANSITO'),
    '162' => array('cod'=>'TV','nom'=>'TRANSVERSAL'),
    '163' => array('cod'=>'UE','nom'=>'PUBLO'),
    '164' => array('cod'=>'UR','nom'=>'URBANIZACION'),
    '165' => array('cod'=>'UT','nom'=>'PUERTO'),
    '166' => array('cod'=>'VA','nom'=>'VIAL'),
    '167' => array('cod'=>'VC','nom'=>'CUEVAS'),
    '168' => array('cod'=>'VD','nom'=>'VIADUCTO'),
    '169' => array('cod'=>'VI','nom'=>'VIA'),
    '170' => array('cod'=>'VL','nom'=>'VILLA'),
    '171' => array('cod'=>'VP','nom'=>'VIA PUBLICA'),
    '172' => array('cod'=>'VR','nom'=>'VERDA'),
    '173' => array('cod'=>'VV','nom'=>'VIVIENDAS'),
    '174' => array('cod'=>'ZN','nom'=>'ZONA')
);

$arrService = array (
        array('code'=>'0000', 'name'=>'Urgente 10'),
        array('code'=>'0015', 'name'=>'Urgente 10 Expedicion'),
        //array('code'=>'0005', 'name'=>'Urgente Hoy'),
        //array('code'=>'0010', 'name'=>'Promociones'),
        array('code'=>'0100', 'name'=>'Urgente 12'),
        array('code'=>'0110', 'name'=>'Urgente 14'),
        array('code'=>'0115', 'name'=>'Urgente 14 Expedicion'),
        array('code'=>'0200', 'name'=>'Urgente 19'),
        array('code'=>'0205', 'name'=>'Urgente 19 Expedicion'),
        //array('code'=>'0210', 'name'=>'Urgente 19 + 40kg'),
        array('code'=>'0220', 'name'=>'Urgente 19 Portugal'),
        array('code'=>'0230', 'name'=>'Bag 19'),
        array('code'=>'0235', 'name'=>'Bag 14'),
        array('code'=>'0300', 'name'=>'Economico'),
        //array('code'=>'0310', 'name'=>'Economico + 40kg'),
        array('code'=>'0350', 'name'=>'Economico Interinsular'),
        //array('code'=>'0400', 'name'=>'Express Documentos'),
        //array('code'=>'0450', 'name'=>'Express 2kg'),
        //array('code'=>'0480', 'name'=>'Caja Express 3kg'),
        //array('code'=>'0490', 'name'=>'Documentos 14'),
        array('code'=>'0800', 'name'=>'eCommerce'),
        array('code'=>'0810', 'name'=>'eCommerce Canje'),
        //array('code'=>'0205', 'name'=>'Urgente 19 Expedición'),
        array('code'=>'0370', 'name'=>'Maritimo Baleares'),
        array('code'=>'0385', 'name'=>'Maritimo Canarias'),
        //array('code'=>'0380', 'name'=>'Maritimo Baleares + 40kg'),
        array('code'=>'0390', 'name'=>'Maritimo Interinsular')
);

