<?php
/**
 * 2011-2018 OBSOLUTIONS WD S.L. All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of OBSOLUTIONS WD S.L. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to OBSOLUTIONS WD S.L.
 * and its suppliers and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from OBSOLUTIONS WD S.L.
 *
 *  @author    OBSOLUTIONS WD S.L. <http://addons.prestashop.com/en/65_obs-solutions>
 *  @copyright 2011-2018 OBSOLUTIONS WD S.L.
 *  @license   OBSOLUTIONS WD S.L. All Rights Reserved
 *  International Registered Trademark & Property of OBSOLUTIONS WD S.L.
 */

$sql = array();

$sql[] = 'CREATE TABLE IF NOT EXISTS `'.pSQL(_DB_PREFIX_.$this->name).'_notify` (
    `id_'.pSQL($this->name).'_notify` int(11) NOT NULL AUTO_INCREMENT,
    `id_customer` int(11) NOT NULL,
    `id_cart` int(11) NOT NULL,
    `id_order` int(11) DEFAULT 0,
    `tpv_order` varchar(25) NOT NULL,
    `amount_cart` decimal(11,2) NOT NULL,
    `amount_paid` decimal(11,2) NOT NULL,
    `amount_refunded` decimal(11,2) NOT NULL DEFAULT 0,
    `error_code` varchar(25) NOT NULL,
    `error_message` varchar(450) NOT NULL,
    `debug_data` TEXT,
    `type` ENUM( \'test\', \'real\', \'unknown\' ) NOT NULL DEFAULT \'unknown\',
    `date_add` datetime NOT NULL,
    `id_tpv` int(11) NULL,
    `shop_id` int(11) NULL,
    `date_tpv` TEXT NOT NULL,
    `hour` TEXT NOT NULL,
    `securePayment` int(1) NULL,
    `transactionType` varchar(1) NOT NULL,
    `cardCountry` varchar(3) NOT NULL,
    `authorisationCode` varchar(6) NOT NULL,
    `consumerLanguage` int(3) NOT NULL,
    `cardType` varchar(1) NOT NULL,
    PRIMARY KEY  (`id_'.pSQL($this->name).'_notify`)
) ENGINE='.pSQL(_MYSQL_ENGINE_).' DEFAULT CHARSET=utf8;';

$sql[] = 'INSERT INTO `'.pSQL(_DB_PREFIX_.$this->name).'_notify` (`id_customer`, `id_cart`,`id_order`,`tpv_order`,
		`amount_cart`, `amount_paid`, `error_code`, `error_message`, `debug_data`, `type`, `date_add`)
		  VALUES (1, 1, 0, "0", 0,0, "TEST", "TEST", "TEST", "test", NOW() )';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'.pSQL(_DB_PREFIX_.$this->name).'_config` (
    `id_'.pSQL($this->name).'_config` int(11) NOT NULL AUTO_INCREMENT,
    `shop_id` INT(11) NOT NULL,
    `sandbox_mode` char(1) NOT NULL,
    `merchant_code` varchar(25) NOT NULL,
    `merchant_name` varchar(75) DEFAULT 0,
    `terminal_number` varchar(25) NOT NULL,
    `merchant_key` varchar(125) NOT NULL,
    `payment_type` CHAR(1) NOT NULL DEFAULT \'C\',
	`min_amount` decimal(17,2) NOT NULL DEFAULT \'0.00\',
	`max_amount` decimal(17,2) NOT NULL DEFAULT \'0.00\',
    `iframe_mode` char(1) NOT NULL,
    `currency_code` varchar(5) NOT NULL DEFAULT 978,
    `currency_iso` varchar(3) NOT NULL DEFAULT "EUR",
	`currency_filter` TINYINT( 1 ) NOT NULL DEFAULT 0,
    `iframe_width` varchar(5) NOT NULL,
    `date_add` datetime NOT NULL,
    `date_upd` datetime NOT NULL,
    `active` TINYINT( 1 ) NOT NULL DEFAULT 0,		
    PRIMARY KEY  (`id_'.pSQL($this->name).'_config`)
) ENGINE='.pSQL(_MYSQL_ENGINE_).' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'.pSQL(_DB_PREFIX_.$this->name).'_config_lang` (
    `id_'.pSQL($this->name).'_config` int(11) NOT NULL,
    `id_lang` int(11) NOT NULL,
    `payment_text` varchar(250) NOT NULL,
    PRIMARY KEY  (`id_'.pSQL($this->name).'_config`, `id_lang`)
) ENGINE='.pSQL(_MYSQL_ENGINE_).' DEFAULT CHARSET=utf8;';

$sql[] = "CREATE TABLE IF NOT EXISTS `".pSQL(_DB_PREFIX_.$this->name)."_config_group` (
		`id_tpv` int(10) unsigned NOT NULL,
		`id_group` int(10) unsigned NOT NULL
		) ENGINE=".pSQL(_MYSQL_ENGINE_)." DEFAULT CHARSET=utf8;";

$sql[] = "CREATE TABLE IF NOT EXISTS `".pSQL(_DB_PREFIX_.$this->name)."_config_carrier` (
		`id_tpv` int(10) unsigned NOT NULL,
		`id_carrier` int(10) unsigned NOT NULL,
		`id_reference` int(10) unsigned NOT NULL
		) ENGINE=".pSQL(_MYSQL_ENGINE_)." DEFAULT CHARSET=utf8;";

$sql[] = "CREATE TABLE IF NOT EXISTS `".pSQL(_DB_PREFIX_.$this->name)."_countries` (
        `name` text NOT NULL,
        `iso` varchar(3) NOT NULL,
        `m49` int(4) NOT NULL
        ) ENGINE=".pSQL(_MYSQL_ENGINE_)." DEFAULT CHARSET=utf8";

$sql[] = "INSERT INTO `".pSQL(_DB_PREFIX_.$this->name)."_countries` (`name`, `iso`, `m49`) VALUES
('Afghanistan', 'AFG', 4),
('Albania', 'ALB', 8),
('Algeria', 'DZA', 12),
('American Samoa', 'ASM', 16),
('Andorra', 'AND', 20),
('Angola', 'AGO', 24),
('Anguilla', 'AIA', 660),
('Antarctica', 'ATA', 10),
('Antigua & Barbuda', 'ATG', 28),
('Argentina', 'ARG', 32),
('Armenia', 'ARM', 51),
('Aruba', 'ABW', 533),
('Australia', 'AUS', 36),
('Austria', 'AUT', 40),
('Azerbaijan', 'AZE', 31),
('Bahamas', 'BHS', 44),
('Bahrain', 'BHR', 48),
('Bangladesh', 'BGD', 50),
('Barbados', 'BRB', 52),
('Belarus', 'BLR', 112),
('Belgium', 'BEL', 56),
('Belize', 'BLZ', 84),
('Benin', 'BEN', 204),
('Bermuda', 'BMU', 60),
('Bhutan', 'BTN', 64),
('Bolivia', 'BOL', 68),
('Bosnia', 'BIH', 70),
('Botswana', 'BWA', 72),
('Bouvet Island', 'BVT', 74),
('Brazil', 'BRA', 76),
('British Indian Ocean Territory', 'IOT', 86),
('British Virgin Islands', 'VGB', 92),
('Brunei', 'BRN', 96),
('Bulgaria', 'BGR', 100),
('Burkina Faso', 'BFA', 854),
('Burundi', 'BDI', 108),
('Cambodia', 'KHM', 116),
('Cameroon', 'CMR', 120),
('Canada', 'CAN', 124),
('Cape Verde', 'CPV', 132),
('Caribbean Netherlands', 'BES', 535),
('Cayman Islands', 'CYM', 136),
('Central African Republic', 'CAF', 140),
('Chad', 'TCD', 148),
('Chile', 'CHL', 152),
('China', 'CHN', 156),
('Christmas Island', 'CXR', 162),
('Cocos (Keeling) Islands', 'CCK', 166),
('Colombia', 'COL', 170),
('Comoros', 'COM', 174),
('Congo - Brazzaville', 'COG', 178),
('Congo - Kinshasa', 'COD', 180),
('Cook Islands', 'COK', 184),
('Costa Rica', 'CRI', 188),
('Croatia', 'HRV', 191),
('Cuba', 'CUB', 192),
('Curaçao', 'CUW', 531),
('Cyprus', 'CYP', 196),
('Czech Republic', 'CZE', 203),
('Côte d’Ivoire', 'CIV', 384),
('Denmark', 'DNK', 208),
('Djibouti', 'DJI', 262),
('Dominica', 'DMA', 212),
('Dominican Republic', 'DOM', 214),
('Ecuador', 'ECU', 218),
('Egypt', 'EGY', 818),
('El Salvador', 'SLV', 222),
('Equatorial Guinea', 'GNQ', 226),
('Eritrea', 'ERI', 232),
('Estonia', 'EST', 233),
('Ethiopia', 'ETH', 231),
('Falkland Islands', 'FLK', 238),
('Faroe Islands', 'FRO', 234),
('Fiji', 'FJI', 242),
('Finland', 'FIN', 246),
('France', 'FRA', 250),
('French Guiana', 'GUF', 254),
('French Polynesia', 'PYF', 258),
('French Southern Territories', 'ATF', 260),
('Gabon', 'GAB', 266),
('Gambia', 'GMB', 270),
('Georgia', 'GEO', 268),
('Germany', 'DEU', 276),
('Ghana', 'GHA', 288),
('Gibraltar', 'GIB', 292),
('Greece', 'GRC', 300),
('Greenland', 'GRL', 304),
('Grenada', 'GRD', 308),
('Guadeloupe', 'GLP', 312),
('Guam', 'GUM', 316),
('Guatemala', 'GTM', 320),
('Guernsey', 'GGY', 831),
('Guinea', 'GIN', 324),
('Guinea-Bissau', 'GNB', 624),
('Guyana', 'GUY', 328),
('Haiti', 'HTI', 332),
('Heard & McDonald Islands', 'HMD', 334),
('Honduras', 'HND', 340),
('Hong Kong', 'HKG', 344),
('Hungary', 'HUN', 348),
('Iceland', 'ISL', 352),
('India', 'IND', 356),
('Indonesia', 'IDN', 360),
('Iran', 'IRN', 364),
('Iraq', 'IRQ', 368),
('Ireland', 'IRL', 372),
('Isle of Man', 'IMN', 833),
('Israel', 'ISR', 376),
('Italy', 'ITA', 380),
('Jamaica', 'JAM', 388),
('Japan', 'JPN', 392),
('Jersey', 'JEY', 832),
('Jordan', 'JOR', 400),
('Kazakhstan', 'KAZ', 398),
('Kenya', 'KEN', 404),
('Kiribati', 'KIR', 296),
('Kuwait', 'KWT', 414),
('Kyrgyzstan', 'KGZ', 417),
('Laos', 'LAO', 418),
('Latvia', 'LVA', 428),
('Lebanon', 'LBN', 422),
('Lesotho', 'LSO', 426),
('Liberia', 'LBR', 430),
('Libya', 'LBY', 434),
('Liechtenstein', 'LIE', 438),
('Lithuania', 'LTU', 440),
('Luxembourg', 'LUX', 442),
('Macau', 'MAC', 446),
('Macedonia', 'MKD', 807),
('Madagascar', 'MDG', 450),
('Malawi', 'MWI', 454),
('Malaysia', 'MYS', 458),
('Maldives', 'MDV', 462),
('Mali', 'MLI', 466),
('Malta', 'MLT', 470),
('Marshall Islands', 'MHL', 584),
('Martinique', 'MTQ', 474),
('Mauritania', 'MRT', 478),
('Mauritius', 'MUS', 480),
('Mayotte', 'MYT', 175),
('Mexico', 'MEX', 484),
('Micronesia', 'FSM', 583),
('Moldova', 'MDA', 498),
('Monaco', 'MCO', 492),
('Mongolia', 'MNG', 496),
('Montenegro', 'MNE', 499),
('Montserrat', 'MSR', 500),
('Morocco', 'MAR', 504),
('Mozambique', 'MOZ', 508),
('Myanmar', 'MMR', 104),
('Namibia', 'NAM', 516),
('Nauru', 'NRU', 520),
('Nepal', 'NPL', 524),
('Netherlands', 'NLD', 528),
('New Caledonia', 'NCL', 540),
('New Zealand', 'NZL', 554),
('Nicaragua', 'NIC', 558),
('Niger', 'NER', 562),
('Nigeria', 'NGA', 566),
('Niue', 'NIU', 570),
('Norfolk Island', 'NFK', 574),
('North Korea', 'PRK', 408),
('Northern Mariana Islands', 'MNP', 580),
('Norway', 'NOR', 578),
('Oman', 'OMN', 512),
('Pakistan', 'PAK', 586),
('Palau', 'PLW', 585),
('Palestine', 'PSE', 275),
('Panama', 'PAN', 591),
('Papua New Guinea', 'PNG', 598),
('Paraguay', 'PRY', 600),
('Peru', 'PER', 604),
('Philippines', 'PHL', 608),
('Pitcairn Islands', 'PCN', 612),
('Poland', 'POL', 616),
('Portugal', 'PRT', 620),
('Puerto Rico', 'PRI', 630),
('Qatar', 'QAT', 634),
('Romania', 'ROU', 642),
('Russia', 'RUS', 643),
('Rwanda', 'RWA', 646),
('Réunion', 'REU', 638),
('Samoa', 'WSM', 882),
('San Marino', 'SMR', 674),
('Saudi Arabia', 'SAU', 682),
('Senegal', 'SEN', 686),
('Serbia', 'SRB', 688),
('Seychelles', 'SYC', 690),
('Sierra Leone', 'SLE', 694),
('Singapore', 'SGP', 702),
('Sint Maarten', 'SXM', 534),
('Slovakia', 'SVK', 703),
('Slovenia', 'SVN', 705),
('Solomon Islands', 'SLB', 90),
('Somalia', 'SOM', 706),
('South Africa', 'ZAF', 710),
('South Georgia & South Sandwich Islands', 'SGS', 239),
('South Korea', 'KOR', 410),
('South Sudan', 'SSD', 728),
('Spain', 'ESP', 724),
('Sri Lanka', 'LKA', 144),
('St. Barthélemy', 'BLM', 652),
('St. Helena', 'SHN', 654),
('St. Kitts & Nevis', 'KNA', 659),
('St. Lucia', 'LCA', 662),
('St. Martin', 'MAF', 663),
('St. Pierre & Miquelon', 'SPM', 666),
('St. Vincent & Grenadines', 'VCT', 670),
('Sudan', 'SDN', 729),
('Suriname', 'SUR', 740),
('Svalbard & Jan Mayen', 'SJM', 744),
('Swaziland', 'SWZ', 748),
('Sweden', 'SWE', 752),
('Switzerland', 'CHE', 756),
('Syria', 'SYR', 760),
('São Tomé & Príncipe', 'STP', 678),
('Taiwan', 'TWN', 158),
('Tajikistan', 'TJK', 762),
('Tanzania', 'TZA', 834),
('Thailand', 'THA', 764),
('Timor-Leste', 'TLS', 626),
('Togo', 'TGO', 768),
('Tokelau', 'TKL', 772),
('Tonga', 'TON', 776),
('Trinidad & Tobago', 'TTO', 780),
('Tunisia', 'TUN', 788),
('Turkey', 'TUR', 792),
('Turkmenistan', 'TKM', 795),
('Turks & Caicos Islands', 'TCA', 796),
('Tuvalu', 'TUV', 798),
('U.S. Outlying Islands', 'UMI', 581),
('U.S. Virgin Islands', 'VIR', 850),
('UK', 'GBR', 826),
('US', 'USA', 840),
('Uganda', 'UGA', 800),
('Ukraine', 'UKR', 804),
('United Arab Emirates', 'ARE', 784),
('Uruguay', 'URY', 858),
('Uzbekistan', 'UZB', 860),
('Vanuatu', 'VUT', 548),
('Vatican City', 'VAT', 336),
('Venezuela', 'VEN', 862),
('Vietnam', 'VNM', 704),
('Wallis & Futuna', 'WLF', 876),
('Western Sahara', 'ESH', 732),
('Yemen', 'YEM', 887),
('Zambia', 'ZMB', 894),
('Zimbabwe', 'ZWE', 716),
('Åland Islands', 'ALA', 248)";

foreach ($sql as $query)
	if (Db::getInstance()->execute($query) == false)
		return false;
